---
- hosts: all
  become: yes

  tasks:
    - name: Install requirements.
      apt:
        state: present
        name:
          - git
          - curl
    - name: Create /etc/pihole directory.
      file:
        path: /etc/pihole
        state: directory
      tags: pihole
    - name: Download pihole installer.
      get_url:
        url: https://install.pi-hole.net
        dest: /tmp/install-pihole.sh
        mode: 0740
      tags: pihole
      

